In [1]:
import  numpy as np
import cvxpy as cv


In [2]:
cv.__version__

'1.0.25'

In [3]:
#Definition your variables
x = cv.Variable(2)

#Defining your objective function
obj = -x[0] - 2*x[1]

obj = cv.Minimize(-x[0] - 2*x[1])

#Defining your constraints
const = [-x[0] + 3*x[1] <= 3,
        x[0] + x[1] <= 5,
        x[0] >= 0,
        x[1] >= 0]

In [4]:
#Assigning a variable to the optimization function
problem = cv.Problem(obj, const)

In [5]:
#solving the optimal solution
problem.solve()

-7.0

In [6]:
#finding the optimal values
x.value

array([3., 2.])

In [7]:

##OPTIMIZING THE LOSS FUNCTION FOR A SIMPLE LINEAR REGRESSION DEVOID OF A BIAS

In [8]:
#generate random values
np.random.seed(1)
n = 50
y_simple = np.random.randn(n)
x_simple = np.random.randn(n)

In [9]:
x_simple.shape, y_simple.shape

((50,), (50,))

In [10]:
w = cv.Variable(n)
obj = cv.Minimize(cv.sum_squares(y_simple - (w*x_simple) / n)
prob = cv.Problem(obj)

SyntaxError: invalid syntax (<ipython-input-10-b1d4e6407fb1>, line 3)

In [11]:
prob.solve()


NameError: name 'prob' is not defined

In [12]:
w.value

NameError: name 'w' is not defined

In [13]:
np.random.seed(1)
n = 50
y = np.random.randn(n)
x = np.random.randn(n)

In [14]:
x.shape

(50,)

In [15]:
w = cv.Variable(1)
b = cv.Variable(1)
obj = cv.Minimize(cv.sum_squares(y - (w*x) + b) / n)
prob = cv.Problem(obj)

In [16]:
problem.solve()

-7.000000000000009

In [17]:
w.value

In [18]:
b.value

In [19]:
#MULTIPLE LINEAR REGRESSION

In [20]:
np.random.seed(1)
n = 150
m = 20
Y = np.random.randn(n)
X = np.random.randn(n,m)

In [21]:
W = cv.Variable(m)
obj = cv.Minimize(cv.square(cv.norm2(Y - X*W)))
PROB = cv.Problem(obj)

In [22]:
PROB.solve()

103.5970136633693

In [23]:
W.value

array([ 0.17466031,  0.10631958,  0.08722336,  0.03084005, -0.03546575,
       -0.04348829, -0.01629189,  0.00305956, -0.08081888,  0.02300616,
        0.00453184,  0.03173734, -0.01098854,  0.07438982,  0.0578941 ,
       -0.05919649, -0.00067602, -0.04605193,  0.01198067, -0.05065962])

In [24]:
#LASSO REGRESSION
np.random.seed(1)
a = 150
b = 20
Y1 = np.random.randn(a)
X1 = np.random.randn(a,b)

In [25]:
w_lasso = cv.Variable(b)
alpha = 0.5
obj_lasso = cv.Minimize((cv.sum_squares(cv.norm(Y1 - (X1 * w_lasso))) + alpha * cv.norm(w_lasso))
prob_lasso = cv.Problem(obj_lasso)

SyntaxError: invalid syntax (<ipython-input-25-3d225fe8ccef>, line 4)

In [26]:
prob_lasso.solve()

NameError: name 'prob_lasso' is not defined

In [27]:
w_lasso.value

NameError: name 'w_lasso' is not defined

In [28]:
##Quadratic Programming

#Ridge regression 
np.random.seed(1)
c = 150
d = 20
Y2 = np.random.randn(c)
X2 = np.random.randn(c,d)

In [29]:
w_ridge = cv.Variable(d)
alpha_2 = 0.5
obj_ridge = cv.Minimize((cv.sum_squares(cv.norm(Y2 - (X2 * w_ridge) ))) + alpha_2 * cv.norm2(w_ridge))
prob_ridge = cv.Problem(obj_ridge)

In [30]:
prob_ridge.solve()

103.7373154326551

In [31]:
w_ridge.value

array([ 0.17349574,  0.10566921,  0.08694261,  0.03062579, -0.03547698,
       -0.04313972, -0.01625238,  0.00287891, -0.08051588,  0.02263038,
        0.00436396,  0.03147548, -0.01108874,  0.07397961,  0.0573734 ,
       -0.05904655, -0.00064257, -0.04547862,  0.01190881, -0.05015558])

In [32]:
##QUADRATIC OPTIMISATION


In [33]:
np.random.seed
k = 150
l = 20
Y3 = np.random.randn(k)
X3 = np.random.randn(l,k)

In [34]:
W_quad = cv.Variable(l)
objective_quad = cv.Minimize((1/2) * cv.square(cv.norm2((X3.T ) * W_quad - Y3)))
PROBLEM = cv.Problem(objective_quad)

In [35]:
PROBLEM.solve()

73.4480141379532

In [36]:
W_quad.value

array([-0.01563927,  0.07050773, -0.1324903 , -0.14005629, -0.0934458 ,
        0.05870437, -0.0288675 , -0.03637339, -0.0349551 , -0.07703684,
        0.02614148,  0.02385759, -0.12583051,  0.13321194,  0.05202856,
       -0.09979245, -0.05190316,  0.02895704,  0.00916003, -0.013711  ])

In [37]:
#COVARIANCE OF X
Q = np.cov(X3, rowvar = True)
b = X3 @ Y3

In [38]:
OBJECTIVE2 = cv.Minimize(0.5 * cv.quad_form(W_quad, Q) - b.T @ W_quad + (0.5 * Y3 @ Y3))
OBJECTIVE_PROBLEM = cv.Problem(OBJECTIVE2)

In [39]:

OBJECTIVE_PROBLEM.solve()

-1171.3638631959489

In [40]:
W_quad.value

array([ -2.33279031,  12.15810497, -20.19370777, -20.87045214,
       -14.82144243,   8.49987531,  -4.25165233,  -5.66536648,
        -6.10885877, -11.79929486,   3.77978789,   3.63492323,
       -18.52114105,  19.61594385,   8.07493095, -14.79784116,
        -7.03775171,   5.34166036,   1.28551497,  -2.05235816])

In [41]:
#Quadratic OPtimization
#minimize 2x1^2 + 2x2^2 - x1*x2

#subject to: 2*x1 + 3x2 >= 1
#            5*x1 + 4*x2 >= 1

In [42]:
#Defining arrays for the constants of the quadratic equation
c = np.array([2, 2, -1])
#creating arrays for q and an array for the constraints A and b
Q = np.array([[2, -1/2], [-1/2, 2]]) ; A = np.array([[2,3], [5,4]]) ; b = np.ones((2,))

In [43]:
#define your variables of the objective function
x = cv.Variable(2)

#creating your minimization objective function
obj11 = cv.Minimize(2*x[0]**2 + 2*x[1]**2 - x[0]*x[1])

#defining your constraints
const11 =[A*x >= b]

In [44]:
#solving the optimization problem
prob11 = cv.Problem(obj11, const11)


In [45]:
#prob11.solve()
#executing this for solution is not feasible  Problem does not follow DCP rules. Specifically:
#The objective is not DCP. Hence we use the cv.quad_form function.

In [46]:
prob111 = cv.Problem(cv.Minimize(cv.quad_form(x,Q)), const11)

In [47]:
prob111.solve()

0.11718750000000003

In [48]:
x.value

array([0.171875, 0.21875 ])

In [49]:
#verifying whether the first condition is true
A@x.value

array([1.      , 1.734375])

In [50]:
#Minimizing using the Lagrange Multipliers

Q1 = np.array([[2, -1/2], [-1/2, 2]]) ; A1 = np.array([[2,3], [5,4]]) ; b1 = np.ones((2,))


In [51]:
##defining the variables for Lambda
lambda1 = cv.Variable(2)

#defining S
S = (A1 @ np.linalg.inv(Q1) @ A1.T) / 4

#Quadratic objective function
obj_Lag = cv.Maximize((lambda1.T @ b1) - (cv.quad_form(lambda1, S)))

#defining the constraint
const_Lag = [lambda1 >= 0]

In [52]:
#Definition of the lagrange function
prob_Lag = cv.Problem(obj_Lag, const_Lag)

In [53]:
#calling  the function to find the optimal solution
prob_Lag.solve()

0.11718750000000003

In [54]:
#finding the values of lambda
lambda1.value

array([2.34375000e-01, 6.62567448e-24])

In [55]:
b - A @ x.value <= 0

array([ True,  True])

In [56]:
lambda1.value >= 0

array([ True,  True])

In [57]:
all(lambda1.value * (b - A @ x.value)) == 0

True

In [58]:
d_l = 2 * x.value.T @ Q - lambda1.value.T @ A
d_l

array([-5.55111512e-17,  0.00000000e+00])

In [ ]:
#Solving problem 1
#minimize 4x1 + 5abs(x2 - 1)
#subject to abs(2x1) + abs(x2 - 3) <= 5

In [59]:
x = cv.Variable(2)
obj_p1 = cv.Minimize( 4*x[0] + 5*cv.abs(x[1] - 1))
cons_p1 = [cv.abs(2 * x[0]) + cv.abs(x[1] - 3) <= 5]
p1 = cv.Problem(obj_p1, cons_p1)


In [60]:
p1.solve()

-6.000000000000001

In [61]:
print("the values of x are: {}".format(x.value))

the values of x are: [-1.5  1. ]


In [62]:
#problem 2
#maximize 7.8x1 + 7.1x2
#subject to
#1/4 x1 + 1/3 x2 <= 90
#1/8 x1 + 1/3 x2 <= 80
#x1 >= 0 or -x1 <= 0
#x2 >= 0 or -x2 <= 0
#let x = product

In [110]:
#DECLARING THE PRODUCT VARIABLE
product = cv.Variable(2)

#SPECIFY THE OBJECTIVE FUNCTION
obj_prob2 = cv.Maximize(7.8*product[0] + 7.1*product[1])

#SPECIFY THE CONSTRAINTS

cons_prob2 = [
    1/4*product[0] + 1/3*product[1] <= 90,
    1/8*product[0] + 1/3*product[1] <= 80,
    product[0] >= 0,
    product[1] >= 0
             ]

#call out the optimization function
p2 = cv.Problem(obj_prob2, cons_prob2)

In [120]:
p2.solve(verbose=True)

iter   objective    pri res    dua res    rho        time
   1  -2.8080e+03   1.36e-13   5.20e-15   7.94e-03   1.26e-04s
  25  -2.8080e+03   1.19e-13   1.91e-14   7.94e-03   2.35e-04s

status:               solved
number of iterations: 25
optimal objective:    -2808.0000
run time:             3.05e-04s
optimal rho estimate: 1.44e-05



2807.9999999999986

In [112]:
print(" the values of product are: {}".format(product.value))

 the values of product are: [3.60000000e+02 2.16483374e-21]


In [113]:
#problem 2 b
#suppose that up to 50 hours of overtime assembly labor can be scheduled at a cost of $7 per hour
#let x3 =  overtime
#maximize 7.8x1 + 7.1x2 - 7x3
#subject to
#1/4 x1 + 1/3 x2 <= 90
#1/8 x1 + 1/3 x2 <= 80
#x3 <= 50
#x1 >= 0 or -x1 <= 0
#x2 >= 0 or -x2 <= 0
#x3 >= 0
#let x = product

In [116]:
#DECLARING THE PRODUCT VARIABLE
product1 = cv.Variable(3)

#SPECIFY THE OBJECTIVE FUNCTION
obj_prob3 = cv.Maximize(7.8*product1[0] + 7.1*product1[1])

#SPECIFY THE CONSTRAINTS
m1 = np.array([[1/4, 1/3, 0], [1/8, 1/3, 0], [-1, 0, 0], [0,-1, 0], [0, 0, 1],[0, 0, -1]])
n1 = np.array([90, 80, 0, 0, 50, 0])

cons_prob3 = [(m1 @ product1) <= n1]

#call out the optimization function
p3 = cv.Problem(obj_prob3, cons_prob3)

In [122]:
p3.solve()

2808.0000000000014

In [123]:
print("the values of product1 are: {}".format(product1))

the values of product1 are: var1228


In [125]:
product1.value


array([ 3.6000000e+02, -1.3718113e-13,  0.0000000e+00])